// <auto-generated />
namespace Mooshak___H37.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class jon1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jon1));
        
        string IMigrationMetadata.Id
        {
            get { return "201605091316385_jon1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
